spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lavi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

sa-token:
  token-name: token
  timeout: 604800
  active-timeout: -1
  is-concurrent: false
  is-share: true
  token-style: uuid
  is-log: true